<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function getTeamGames()
    {
        return $this->createQueryBuilder('g')
            ->select('g, s, t')
            ->leftjoin('g.scores', 's')
            ->join('s.team', 't')
//            ->where('t = ?1')
//            ->setParameter(1, $team)
            ->getQuery()
            ->getResult();
    }
}
