<?php

namespace AppBundle\Entity;

/**
 * GamescoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameScoreRepository extends \Doctrine\ORM\EntityRepository
{
}
