<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{

    public function getTeamWithPlayers($teamName)
    {
        return $this->createQueryBuilder('t')
            ->select('t, c, p')
            ->leftjoin('t.country', 'c')
            ->join('t.players', 'p')
            ->where('t.name = ?1')
            ->setParameter(1, $teamName)
            ->getQuery()
            ->getSingleResult();
    }
}
